#!/usr/bin/env python3
"""Build the Sacred Valley map geometry for ValleyMap.svelte.

BUILD-TIME ONLY. This script talks to the network; the website never does.
It fetches the Vilcanota/Urubamba river and the valley towns from OSM, reduces
them to a handful of numbers, and prints a paste-ready TypeScript block that
gets checked into `src/lib/components/ValleyMap.svelte`. The published page
therefore renders the map fully offline, which is what local-first requires.

Re-run only to refresh the geometry:

    python3 scripts/build-valley-map.py           # print the block, using ./.cache
    python3 scripts/build-valley-map.py --write   # patch ValleyMap.svelte in place
    python3 scripts/build-valley-map.py --fetch   # force a fresh OSM pull

Data © OpenStreetMap contributors, ODbL 1.0 — https://osm.org/copyright
The rendered map MUST carry that attribution. It is a licence obligation.
"""
import json
import math
import os
import sys
import urllib.parse
import urllib.request

OVERPASS = 'https://overpass-api.de/api/interpreter'
COMPONENT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'src', 'lib', 'components', 'ValleyMap.svelte')
BEGIN = '  // ─── generated by scripts/build-valley-map.py — do not hand-edit ───'
END = '  // ─── end generated ───'
UA = 'AyniCollective/0.1 (+https://github.com/AyniCollective) valley-map-build'
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.cache')

# Wide pull box (the river is fetched beyond the frame so the clip below has
# real geometry to cut, rather than ending at the frame edge).
PULL = (-13.60, -72.40, -13.10, -71.70)  # s, w, n, e
# The drawn frame: Ollantaytambo (NW) .. Pisac (SE), Calca near the middle.
WIN = dict(s=-13.46, w=-72.32, n=-13.21, e=-71.81)
LAT0 = -13.33            # latitude the cos() correction is taken at
# The frame is fitted to the data, not the other way round: width is fixed and
# height falls out of the valley's own proportions, so the drawing has no dead
# margin. PAD_Y leaves headroom for the town labels, which sit above the dots.
W, PAD_X, PAD_Y = 1000, 44, 74
EPSILON = 1.6            # Douglas-Peucker tolerance, in final SVG units
TOWNS = ('Ollantaytambo', 'Urubamba', 'Yucay', 'Calca', 'Pisac')

QUERIES = {
    'river': f'[out:json][timeout:80];(way["waterway"="river"]'
             f'["name"~"Vilcanota|Urubamba"]{PULL};);out geom;',
    'towns': f'[out:json][timeout:50];(node["place"~"^(town|village|city)$"]{PULL};);out;',
}


def overpass(key, force=False):
    """Fetch a query, caching the raw JSON so reruns don't hammer Overpass."""
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, f'{key}.json')
    if os.path.exists(path) and not force:
        return json.load(open(path))
    body = urllib.parse.urlencode({'data': QUERIES[key]}).encode()
    req = urllib.request.Request(OVERPASS, data=body, headers={'User-Agent': UA})
    print(f'  fetching {key} from Overpass...', file=sys.stderr)
    with urllib.request.urlopen(req, timeout=120) as r:
        data = json.load(r)
    json.dump(data, open(path, 'w'))
    return data


def chain(ways):
    """Join the river ways into one polyline.

    OSM splits the river into ways that SHARE a node at each join, so exact
    equality is the correct test. A distance tolerance looks more forgiving but
    is actually worse: it mis-joins at meanders and silently drops segments
    (observed: 3 of 6 ways joined, wrong extent).
    """
    segs = [[(p['lat'], p['lon']) for p in w['geometry']] for w in ways]
    line, moved = segs.pop(0), True
    while segs and moved:
        moved = False
        for i, g in enumerate(segs):
            if g[0] == line[-1]:    line = line + g[1:]
            elif g[-1] == line[-1]: line = line + g[::-1][1:]
            elif g[-1] == line[0]:  line = g[:-1] + line
            elif g[0] == line[0]:   line = g[::-1][:-1] + line
            else:                   continue
            segs.pop(i)
            moved = True
            break
    return line, len(segs)


def clip(pts):
    """Longest continuous run inside the frame — the river enters and exits once."""
    inside = lambda p: WIN['s'] <= p[0] <= WIN['n'] and WIN['w'] <= p[1] <= WIN['e']
    runs, cur = [], []
    for p in pts:
        if inside(p):
            cur.append(p)
        elif cur:
            runs.append(cur)
            cur = []
    if cur:
        runs.append(cur)
    return max(runs, key=len) if runs else []


def rdp(pts, eps):
    """Douglas-Peucker: drop points that don't change the line's shape."""
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    dmax, idx = 0.0, 0
    for i, (x, y) in enumerate(pts[1:-1], 1):
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / norm
        if d > dmax:
            dmax, idx = d, i
    return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps) if dmax > eps else [pts[0], pts[-1]]


def smooth(pts):
    """Catmull-Rom through the points as cubic beziers, so the river reads as
    drawn by hand rather than as a chain of straight segments."""
    d = [f'M{pts[0][0]:.1f} {pts[0][1]:.1f}']
    for i in range(len(pts) - 1):
        p0 = pts[i - 1] if i else pts[i]
        p1, p2 = pts[i], pts[i + 1]
        p3 = pts[i + 2] if i + 2 < len(pts) else p2
        d.append('C%.1f %.1f %.1f %.1f %.1f %.1f' % (
            p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6,
            p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6,
            p2[0], p2[1]))
    return ''.join(d)


def main():
    force = '--fetch' in sys.argv
    ways = [w for w in overpass('river', force)['elements'] if w.get('geometry')]
    nodes = overpass('towns', force)['elements']

    line, unjoined = chain(ways)
    if unjoined:
        print(f'WARNING: {unjoined} river way(s) did not join', file=sys.stderr)
    win = clip(line)

    # Equirectangular with cos(lat) correction. At this scale (~55 km) the
    # error against a proper projection is well under a pixel, and it keeps the
    # output to two numbers per point.
    k = math.cos(math.radians(LAT0))
    flat = lambda lat, lon: ((lon - WIN['w']) * k, WIN['n'] - lat)

    river_flat = [flat(*p) for p in win]
    towns = {n['tags']['name']: (n['lat'], n['lon'], n['tags'].get('ele'))
             for n in nodes if n['tags'].get('name') in TOWNS}
    town_flat = {n: flat(c[0], c[1]) for n, c in towns.items()}

    # Fit river + towns together so no label lands outside the frame.
    allpts = river_flat + list(town_flat.values())
    xs, ys = [p[0] for p in allpts], [p[1] for p in allpts]
    sx, sy = max(xs) - min(xs), max(ys) - min(ys)
    s = (W - 2 * PAD_X) / sx
    H = round(sy * s + 2 * PAD_Y)
    ox, oy = PAD_X - min(xs) * s, PAD_Y - min(ys) * s
    to_svg = lambda p: (p[0] * s + ox, p[1] * s + oy)

    proj = [to_svg(p) for p in river_flat]
    simple = rdp(proj, EPSILON)
    path = smooth(simple)
    marks = {n: to_svg(p) for n, p in town_flat.items()}

    print(f'river: {len(line)} pts chained -> {len(win)} in frame -> '
          f'{len(simple)} after simplify ({len(path)} chars)', file=sys.stderr)

    # Valley walls: the same spine, brutally simplified, offset perpendicular in
    # the component. Drawn from the real river so the walls follow the real
    # valley instead of being invented squiggles.
    ridge = smooth(rdp(proj, 16))

    # Scale bar. One unit of `flat` space is one degree of latitude; 1 degree of
    # latitude is ~110.57 km at this latitude, and `s` converts flat -> SVG.
    km_per_unit = 110.57 / s
    bar_km = 10
    bar_units = bar_km / km_per_unit

    rows = []
    for name, (x, y) in sorted(marks.items(), key=lambda kv: kv[1][0]):
        lat, lon, ele = towns[name]
        rows.append(f"  {{ name: '{name}', x: {x:.1f}, y: {y:.1f}, "
                    f"lat: {lat}, lon: {lon}, ele: {ele} }},")

    block = '\n'.join([
        BEGIN,
        f'  const VIEW = {{ w: {W}, h: {H} }};',
        "  const RIVER =",
        f"    '{path}';",
        '  const RIDGE =',
        f"    '{ridge}';",
        f'  const SCALE = {{ km: {bar_km}, units: {bar_units:.1f} }}; '
        f'// {km_per_unit:.4f} km per SVG unit',
        '  const TOWNS = [',
        '\n'.join('  ' + r for r in rows),
        '  ];',
        END,
    ])

    if '--write' in sys.argv:
        source = open(COMPONENT).read()
        start, end = source.find(BEGIN), source.find(END)
        if start == -1 or end == -1:
            print(f'ERROR: generated markers not found in {COMPONENT}', file=sys.stderr)
            return 1
        open(COMPONENT, 'w').write(source[:start] + block + source[end + len(END):])
        print(f'wrote generated block into {COMPONENT}', file=sys.stderr)
    else:
        print(block)
        print('\n(pass --write to patch the component in place)', file=sys.stderr)


if __name__ == '__main__':
    main()
