<script lang="ts">
  /**
   * ValleyMap — the Sacred Valley, drawn.
   *
   * A hand-drawn map in the design tokens, in the same craft register as
   * PatternDivider: SVG, `var(--color-*)` throughout, no raster tiles, no map
   * library, no runtime network call. It renders identically offline, which is
   * what local-first requires of a core section.
   *
   * The geometry is REAL, not sketched. The river path, the valley-wall spine,
   * the town positions and the scale bar are all generated from OpenStreetMap
   * data by `scripts/build-valley-map.py` and pasted in below as constants.
   * Sanity check on the projection: Ollantaytambo to Pisac measures 53.6 km
   * here against ~55 km on the ground.
   *
   * Google Maps is deliberately NOT the source — its terms forbid deriving
   * works from Maps content. It is only ever an outbound link (see
   * ContactSection), which no licence restricts.
   *
   * Attribution below the frame is an ODbL licence obligation, not decoration.
   * Do not remove it — and it is not in the catalog either, because its
   * wording is prescribed by the licence rather than chosen by us. The town
   * names, the compass letter and the scale bar stay here for the same kind of
   * reason: geography and units, not prose.
   */
  import { t, DEFAULT_LOCALE } from '$lib/i18n';

  /* $derived, not a plain const: the locale is a property of the URL and
   * becomes dynamic in Phase 3, at which point this recomputes on its own. */
  const m = $derived(t(DEFAULT_LOCALE).home.map);

  // ─── generated by scripts/build-valley-map.py — do not hand-edit ───
  const VIEW = { w: 1000, h: 588 };
  const RIVER =
    'M956.0 513.8C954.0 511.6 946.1 503.8 944.2 500.2C942.3 496.6 946.9 495.1 944.8 492.3C942.7 489.4 935.0 487.3 931.6 483.1C928.2 478.9 927.4 470.7 924.5 467.1C921.5 463.6 917.0 465.0 913.9 462.0C910.8 459.0 910.6 452.4 905.8 449.2C901.0 445.9 893.3 444.4 885.1 442.5C876.9 440.6 863.2 439.5 856.7 437.9C850.1 436.3 853.0 438.0 845.6 432.8C838.2 427.7 818.8 412.9 812.1 407.0C805.5 401.0 807.0 400.2 805.8 397.1C804.6 393.9 806.3 391.9 805.0 387.8C803.8 383.8 799.8 375.6 798.2 372.9C796.7 370.1 798.1 370.8 795.7 371.5C793.2 372.2 787.9 377.9 783.5 377.0C779.2 376.0 772.4 372.1 769.3 366.0C766.3 359.9 767.3 345.5 765.0 340.2C762.7 334.9 757.5 336.5 755.4 334.2C753.3 331.8 754.1 327.8 752.5 326.2C750.8 324.6 748.6 327.9 745.6 324.5C742.6 321.1 737.8 310.4 734.6 305.9C731.4 301.3 731.3 300.5 726.5 297.2C721.7 294.0 709.8 290.2 705.8 286.5C701.8 282.7 702.4 278.4 702.5 274.8C702.7 271.2 707.0 267.0 706.9 264.8C706.7 262.7 704.1 262.0 701.6 261.9C699.1 261.7 694.5 262.7 691.7 263.9C688.9 265.0 688.5 268.4 684.8 268.7C681.2 269.0 674.6 265.9 669.8 265.7C665.1 265.5 659.7 267.7 656.6 267.7C653.5 267.8 656.1 270.2 651.4 266.0C646.6 261.9 634.3 247.2 628.0 242.6C621.7 238.1 618.2 239.0 613.5 238.7C608.9 238.4 604.8 241.4 600.1 240.8C595.4 240.2 588.8 235.6 585.2 235.3C581.6 235.0 580.7 236.2 578.5 238.9C576.4 241.6 574.9 249.0 572.3 251.7C569.6 254.4 565.2 252.3 562.6 255.1C560.0 258.0 558.5 265.7 556.6 268.6C554.8 271.5 552.8 271.6 551.4 272.4C550.0 273.1 549.2 274.1 548.1 273.2C546.9 272.3 545.8 268.1 544.5 266.9C543.1 265.7 543.5 265.6 540.1 266.0C536.7 266.4 529.6 266.9 524.1 269.5C518.7 272.1 512.2 279.9 507.4 281.7C502.6 283.5 498.5 280.0 495.2 280.4C492.0 280.8 491.0 286.7 488.1 284.0C485.2 281.4 481.7 269.6 477.8 264.4C473.9 259.3 469.1 255.8 464.6 253.0C460.1 250.2 455.1 249.9 450.9 247.3C446.8 244.8 443.3 239.2 439.6 237.8C435.9 236.3 431.2 239.3 428.8 238.9C426.4 238.4 428.4 235.9 425.4 235.2C422.3 234.5 414.8 236.5 410.5 234.7C406.1 232.9 403.2 224.8 399.3 224.2C395.5 223.6 390.5 230.4 387.3 231.0C384.1 231.6 382.2 228.3 380.0 227.9C377.9 227.6 375.9 231.3 374.3 229.1C372.8 226.9 373.6 219.5 370.7 214.8C367.8 210.1 359.4 203.6 357.0 200.7C354.6 197.8 358.3 198.7 356.4 197.2C354.6 195.6 350.3 192.0 345.7 191.2C341.1 190.4 331.7 194.5 328.8 192.2C326.0 189.9 329.5 180.6 328.6 177.3C327.7 173.9 325.5 172.6 323.3 172.1C321.0 171.6 317.3 174.1 315.1 174.1C313.0 174.2 313.2 171.0 310.5 172.5C307.8 174.0 302.2 181.2 299.1 183.2C296.0 185.1 293.7 182.9 291.9 184.1C290.0 185.2 288.9 190.8 288.0 190.1C287.1 189.5 287.2 182.7 286.4 180.3C285.5 177.9 284.7 175.9 282.9 175.7C281.0 175.6 280.0 178.8 275.1 179.6C270.3 180.4 263.6 184.7 253.7 180.6C243.7 176.5 226.3 161.0 215.5 155.1C204.6 149.2 194.4 146.8 188.7 145.3C183.0 143.7 184.0 146.1 181.2 145.6C178.5 145.1 174.9 143.9 172.2 142.2C169.5 140.6 167.3 135.6 164.9 135.8C162.6 135.9 163.4 141.3 158.2 143.2C152.9 145.0 140.1 147.5 133.4 146.9C126.7 146.2 121.0 141.2 118.2 139.0C115.4 136.9 118.7 136.1 116.7 134.1C114.8 132.1 108.6 128.8 106.6 127.0C104.6 125.1 109.1 124.8 104.8 123.0C100.4 121.2 83.9 119.3 80.7 116.3C77.5 113.3 86.6 109.0 85.7 104.9C84.8 100.8 80.7 96.4 75.4 91.6C70.2 86.9 59.3 79.4 54.0 76.5C48.8 73.6 45.7 74.4 44.0 74.0';
  const RIDGE =
    'M956.0 513.8C947.6 503.1 924.2 462.7 905.8 449.2C887.4 435.7 868.3 446.7 845.6 432.8C822.9 419.0 793.3 394.5 769.3 366.0C745.3 337.5 732.3 283.7 701.6 261.9C670.9 240.1 610.2 233.6 585.2 235.3C560.1 237.1 567.6 264.2 551.4 272.4C535.2 280.5 506.7 289.8 488.1 284.0C469.5 278.2 458.6 246.9 439.6 237.8C420.7 228.6 393.7 240.0 374.3 229.1C354.9 218.2 337.6 178.6 323.3 172.1C308.9 165.6 314.4 196.2 288.0 190.1C261.6 184.1 190.7 143.0 164.9 135.8C139.1 128.6 153.6 157.1 133.4 146.9C113.3 136.6 58.9 86.1 44.0 74.0';
  const SCALE = { km: 10, units: 170.0 }; // 0.0588 km per SVG unit
  const TOWNS = [
    { name: 'Ollantaytambo', x: 142.3, y: 135.6, lat: -13.2586458, lon: -72.2636012, ele: 2846 },
    { name: 'Urubamba', x: 412.3, y: 224.5, lat: -13.305953, lon: -72.1159706, ele: 2872 },
    { name: 'Yucay', x: 469.4, y: 252.9, lat: -13.3210838, lon: -72.0847651, ele: 2858 },
    { name: 'Calca', x: 704.9, y: 254.1, lat: -13.3216818, lon: -71.9560084, ele: 2932 },
    { name: 'Pisac', x: 897.9, y: 440.8, lat: -13.4210472, lon: -71.850496, ele: 2977 },
  ];
  // ─── end generated ───

  /** Label offsets, hand-tuned against the drawn river.
   *
   * Urubamba and Yucay sit ~57 units apart, so one label goes above the river
   * and the other below or they collide. Ollantaytambo and Pisac are the two
   * ends of the drawn reach, where the river runs diagonally straight through
   * where a centred label would sit, so both are pushed off to one side
   * instead of above or below. */
  type LabelOffset = { dx?: number; dy: number; anchor: 'start' | 'middle' | 'end' };
  const LABEL: Record<string, LabelOffset> = {
    Ollantaytambo: { dx: 16, dy: -28, anchor: 'start' },
    Urubamba: { dy: -26, anchor: 'middle' },
    Yucay: { dy: 40, anchor: 'middle' },
    Calca: { dy: -38, anchor: 'middle' },
    Pisac: { dx: -18, dy: 10, anchor: 'end' },
  };

  /** The valley walls are the river's own spine, offset perpendicular to its
   * NW-SE run — so the ridges follow the real valley rather than invented
   * squiggles. Two per side, the outer pair fainter, for depth.
   *
   * Offsets are in SVG units, which SCALE fixes to ~0.059 km each: the inner
   * pair sits ~5 km off the river, the outer ~10 km, which is roughly where the
   * valley walls actually stand. Re-tune these if the frame is refitted. */
  const RIDGES = [
    { dx: 48, dy: -104, opacity: 0.55 },
    { dx: 90, dy: -198, opacity: 0.3 },
    { dx: -48, dy: 104, opacity: 0.55 },
    { dx: -90, dy: 198, opacity: 0.3 },
  ];

  /** Marginalia baseline, kept relative to the generated frame height so a
   * refit never strands the compass and scale bar mid-map. */
  const MARGIN_Y = VIEW.h - 44;

  const HOME = TOWNS.find((t) => t.name === 'Calca')!;
</script>

<figure class="valley">
  <div class="valley-frame">
    <svg
      viewBox="0 0 {VIEW.w} {VIEW.h}"
      class="valley-svg"
      role="img"
      aria-label={m.label}
    >
      <!-- Valley walls -->
      <g fill="none" stroke="var(--color-line-2)" stroke-linecap="round">
        {#each RIDGES as r}
          <path
            d={RIDGE}
            transform="translate({r.dx} {r.dy})"
            stroke-width="1.5"
            opacity={r.opacity}
          />
        {/each}
      </g>

      <!-- Río Vilcanota / Urubamba — the same river, renamed mid-valley -->
      <path
        d={RIVER}
        fill="none"
        stroke="var(--slate)"
        stroke-width="3"
        stroke-linecap="round"
        stroke-linejoin="round"
      />

      <!-- Towns. Calca is the one clay mark in the composition. -->
      {#each TOWNS as town}
        {@const home = town.name === 'Calca'}
        <g>
          {#if home}
            <circle
              cx={town.x}
              cy={town.y}
              r="21"
              fill="none"
              stroke="var(--clay)"
              stroke-width="2"
              opacity="0.45"
            />
          {/if}
          <circle
            cx={town.x}
            cy={town.y}
            r={home ? 9 : 5}
            fill={home ? 'var(--clay)' : 'var(--color-ink-2)'}
          />
          <text
            x={town.x + (LABEL[town.name].dx ?? 0)}
            y={town.y + LABEL[town.name].dy}
            text-anchor={LABEL[town.name].anchor}
            class:home
            class="town-label"
          >
            {town.name}
          </text>
        </g>
      {/each}

      <!-- Compass and scale, bottom-left, quiet -->
      <g class="marginalia">
        <path
          d="M56 {MARGIN_Y} L56 {MARGIN_Y - 34} M56 {MARGIN_Y - 34} L50 {MARGIN_Y - 24}
             M56 {MARGIN_Y - 34} L62 {MARGIN_Y - 24}"
          fill="none"
          stroke="var(--color-ink-2)"
          stroke-width="2"
          stroke-linecap="round"
          opacity="0.6"
        />
        <text x="56" y={MARGIN_Y + 26} text-anchor="middle" class="margin-label">N</text>
        <path
          d="M110 {MARGIN_Y} h{SCALE.units} M110 {MARGIN_Y - 6} v12
             M{110 + SCALE.units} {MARGIN_Y - 6} v12"
          fill="none"
          stroke="var(--color-ink-2)"
          stroke-width="2"
          opacity="0.6"
        />
        <text
          x={110 + SCALE.units / 2}
          y={MARGIN_Y + 26}
          text-anchor="middle"
          class="margin-label"
        >
          {SCALE.km} km
        </text>
      </g>
    </svg>
  </div>

  <figcaption class="valley-caption">
    <span>
      Calca, Valle Sagrado · {Math.abs(HOME.lat).toFixed(4)}° S,
      {Math.abs(HOME.lon).toFixed(4)}° W
    </span>
    <!-- ODbL obligation. Do not remove. -->
    <span class="valley-credit">Map data © OpenStreetMap contributors</span>
  </figcaption>
</figure>

<style>
  .valley {
    margin: 0;
  }

  .valley-frame {
    border: 1.5px solid var(--color-line-2);
    border-radius: var(--radius);
    background: var(--surface-2);
    overflow: hidden;
  }

  .valley-svg {
    display: block;
    width: 100%;
    height: auto;
  }

  /* Sizes are in SVG user units, not pixels: the frame is 1000 units wide and
   * renders around 560px in the contact grid, so a unit is roughly half a
   * pixel. These look large in the markup and read correctly on screen. */
  .town-label {
    font-family: var(--font-display);
    font-size: 26px;
    fill: var(--color-ink-2);
  }

  .town-label.home {
    font-size: 36px;
    fill: var(--color-ink);
  }

  .margin-label {
    font-family: var(--font-text);
    font-size: 20px;
    letter-spacing: var(--tracking-wide);
    fill: var(--color-ink-2);
    opacity: 0.7;
  }

  .valley-caption {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    gap: var(--spacing-s-2) var(--spacing-s-4);
    margin-top: var(--spacing-s-3);
    font-size: var(--text-xs);
    color: var(--text-3);
  }

  .valley-credit {
    opacity: 0.75;
  }

  /* Narrow viewports render the same 1000-unit frame in far less space, so the
   * lettering has to grow in user units to stay legible. */
  @media (max-width: 700px) {
    .town-label {
      font-size: 34px;
    }
    .town-label.home {
      font-size: 44px;
    }
    .margin-label {
      font-size: 26px;
    }
  }
</style>
